#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# This file is part of IsCoder.

# IsCoder is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# IsCoder is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Author(s): Iven Day (Xu Lijian) <ivenvd@gmail.com>
# Copyright (C) 2009 Iven Day

import pygtk
pygtk.require('2.0')
import gtk

if gtk.pygtk_version < (2,12,0):
    raise SystemExit(' * Error: PyGtk 2.12.0 or later required')

try:
    import IsCoder
except ImportError:
    raise SystemExit(' * Error: the "IsCoder" module is missing. Check if it is installed properly.')

main_win = IsCoder.MainWin()
main_win.show_all()

gtk.main()
